name: Integration Test for PR Automated Comments

on:
  pull_request:
    types: [opened, ready_for_review, closed]

jobs:
  test-pr-comments:
    name: Test PR Comments
    if: github.event_name == 'pull_request'
    uses: RequestNetwork/auto-comments/.github/workflows/pr-auto-comments.yml@main
    with:
      org_name: "RequestNetwork"
      first_pr_comment: |
        # [TEST] Welcome to your first contribution!

        Thank you @{{username}} for submitting your first pull request to the {{repository}} repository.

        This is a test of the automated comment system. This comment was triggered by the integration test workflow.

        Repository: {{repository}}
        Organization: {{org}}

      ready_for_review_comment: |
        # [TEST] PR Ready for Review

        This PR from @{{username}} is now ready for review in the {{repository}} repository.

        This is a test of the automated comment system. This comment was triggered by the integration test workflow.

      merged_pr_comment: |
        # [TEST] PR Successfully Merged!

        Congratulations @{{username}}! Your PR to {{repository}} has been merged.

        This is a test of the automated comment system. This comment was triggered by the integration test workflow.
    secrets:
      token: ${{ secrets.GH_PAT }}
